az-configuration:
- name: ' pks-az1'
  iaas_configuration_name: default
  clusters:
  - cluster: Cluster
    drs_rule: SHOULD
    guid: 943d1443da3bf954ba36
    host_group: null
    resource_pool: pks-az1
  guid: 131ca33f5147179b0a1b
- name: pks-az2
  iaas_configuration_name: default
  clusters:
  - cluster: Cluster
    drs_rule: SHOULD
    guid: 877a099f115f32e8f2a9
    host_group: null
    resource_pool: pks-az2
  guid: 41555c28b64ac1b98138
- name: pks-az3
  iaas_configuration_name: default
  clusters:
  - cluster: Cluster
    drs_rule: SHOULD
    guid: 302f0b4ba9af7cfaec8b
    host_group: null
    resource_pool: pks-az3
  guid: 7bcd1513342b020514c2
iaas-configurations:
- additional_cloud_properties: {}
  bosh_disk_path: ((iaas-configurations_0_bosh_disk_path))
  bosh_template_folder: ((iaas-configurations_0_bosh_template_folder))
  bosh_vm_folder: ((iaas-configurations_0_bosh_vm_folder))
  datacenter: ((iaas-configurations_0_datacenter))
  disk_type: ((iaas-configurations_0_disk_type))
  ephemeral_datastores_string: ((iaas-configurations_0_ephemeral_datastores_string))
  name: ((iaas-configurations_0_name))
  nsx_address: ((iaas-configurations_0_nsx_address))
  nsx_ca_certificate: ((iaas-configurations_0_nsx_ca_certificate))
  nsx_mode: ((iaas-configurations_0_nsx_mode))
  nsx_networking_enabled: ((iaas-configurations_0_nsx_networking_enabled))
  nsx_t_auth_type: ((iaas-configurations_0_nsx_t_auth_type))
  nsx_username: ((iaas-configurations_0_nsx_username))
  persistent_datastores_string: ((iaas-configurations_0_persistent_datastores_string))
  ssl_verification_enabled: ((iaas-configurations_0_ssl_verification_enabled))
  vcenter_host: ((iaas-configurations_0_vcenter_host))
  vcenter_username: ((iaas-configurations_0_vcenter_username))
network-assignment:
  network:
    name: PKS-Infrastructure
  other_availability_zones: []
  singleton_availability_zone:
    name: ' pks-az1'
networks-configuration:
  icmp_checks_enabled: true
  networks:
  - name: PKS-Infrastructure
    subnets:
    - iaas_identifier: PKS-Infrastructure
      cidr: 172.16.1.0/24
      dns: 10.192.2.10, 10.192.2.11
      gateway: 172.16.1.1
      reserved_ip_ranges: 172.16.1.1-172.16.1.10
      availability_zone_names:
      - ' pks-az1'
  - name: PKS-Services
    subnets:
    - iaas_identifier: PKS-Services
      cidr: 172.16.2.0/24
      dns: 10.192.2.10, 10.192.2.11
      gateway: 172.16.2.1
      reserved_ip_ranges: 172.16.2.1-172.16.2.10
      availability_zone_names:
      - ' pks-az1'
properties-configuration:
  director_configuration:
    blobstore_type: local
    bosh_director_recreate_on_next_deploy: false
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    database_type: internal
    director_worker_count: 5
    encryption:
      keys: []
      providers: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    job_configuration_on_tmpfs: false
    keep_unreachable_vms: false
    local_blobstore_options:
      enable_signed_urls: true
    metrics_server_enabled: true
    ntp_servers_string: time.svc.pivotal.io
    post_deploy_enabled: true
    resurrector_enabled: false
    retry_bosh_deploys: true
    skip_director_drain: false
    system_metrics_runtime_enabled: true
  dns_configuration:
    excluded_recursors: []
    handlers: []
  security_configuration:
    generate_vm_passwords: ((properties-configuration_security_configuration_generate_vm_passwords))
    opsmanager_root_ca_trusted_certs: true
  syslog_configuration:
    enabled: false
resource-configuration:
  compilation:
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
    swap_as_percent_of_memory_size: automatic
  director:
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
vmextensions-configuration: []
vmtypes-configuration: {}

